### ISSUE TITLE
offckb create my-ckb-dapp

### ISSUE THREAD

**Issue by mrqinxd** [RetricSu/offckb#101]
When offckb creates my-ckb-dapp
but
error：/usr/local/lib/node_modules/@offckb/cli/dist/util/template.js:26
            throw new Error(`Error fetching JSON: ${error.message}`);
                  ^
Error: Error fetching JSON: 
    at /usr/local/lib/node_modules/@offckb/cli/dist/util/template.js:26:19
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/@offckb/cli/dist/util/template.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I don't ask. Why
node-Version:v20.13.1

**Comment by mrqinxd** [comment]
and 
offckb node               
/bin/sh: /usr/local/lib/node_modules/@offckb/cli/target/ckb/ckb: No such file or directory
/usr/local/lib/node_modules/@offckb/cli/target/ckb/ckb not found, download and install the new version 0.113.1..

**Comment by RetricSu** [comment]
can you connect to github in your terminal? it looks like a network issue to me

**Comment by mrqinxd** [comment]
Thank you for your reply! I can ping, wget can also, do I need to uninstall and reinstall the lower version? offckb 0.2.6.

**Comment by RetricSu** [comment]
`0.2.6` is fine. The command will make request to github repo to get some information https://github.com/RetricSu/offckb/blob/master/src/util/template.ts#L21 The log shows that it has some problem to make that connection

**Comment by RetricSu** [comment]
to be more specific, can you connect to `raw.githubusercontent.com` in your terminal?

**Comment by mrqinxd** [comment]
Thank you very much for your reply, is my end cannot visit: raw.githubusercontent.com, I have carried on the repair. Now it has been able to create normally, but there is a problem with my environment. 0.2.6 No problem

**Comment by mrqinxd** [comment]
In addition, the offckb node also seemed to work after I waited a few minutes

**Comment by RetricSu** [comment]
> In addition, the offckb node also seemed to work after I waited a few minutes

yea it needs to download ckb binary from network for the first time. after the first time, it should be instantly to run `offckb node`
