### ISSUE TITLE
offckb create my-dapp fail

### ISSUE THREAD

**Issue by TheLastHobbit** [RetricSu/offckb#102]
I have a problem in creating a new project according to the tutorial:offckb create my-dapp

/opt/homebrew/lib/node_modules/@offckb/cli/dist/util/template.js:26
            throw new Error(Error fetching JSON: ${error.message});
                  ^

Error: Error fetching JSON: Maximum number of redirects exceeded
    at /opt/homebrew/lib/node_modules/@offckb/cli/dist/util/template.js:26:19
    at Generator.throw (<anonymous>)
    at rejected (/opt/homebrew/lib/node_modules/@offckb/cli/dist/util/template.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.4

**Comment by RetricSu** [comment]
seem like a network problem.

can you connect to `raw.githubusercontent.com` from your terminal?

checkout the similar issue
- https://github.com/RetricSu/offckb/issues/101

**Comment by TheLastHobbit** [comment]
> seem like a network problem.
> 
> can you connect to `raw.githubusercontent.com` from your terminal?
> 
> checkout the similar issue
> 
> * [offckb create my-ckb-dapp #101](https://github.com/RetricSu/offckb/issues/101)

ok ，I found I couldn't link to raw.githubusercontent.com Even though I've used the vpn，I tried many ways, but I couldn't ping it，Can you give me some advice? Thank you。

**Comment by RetricSu** [comment]
maybe try something like proxychains? or set the vpn as your system proxy?

**Comment by TheLastHobbit** [comment]
my-offckb-project % ping raw.githubusercontent.com
PING raw.githubusercontent.com (182.43.124.6): 56 data bytes
64 bytes from 182.43.124.6: icmp_seq=0 ttl=51 time=16.475 ms
64 bytes from 182.43.124.6: icmp_seq=1 ttl=51 time=15.755 ms
64 bytes from 182.43.124.6: icmp_seq=2 ttl=51 time=16.508 ms
64 bytes from 182.43.124.6: icmp_seq=3 ttl=51 time=16.062 ms
64 bytes from 182.43.124.6: icmp_seq=4 ttl=51 time=15.737 ms
64 bytes from 182.43.124.6: icmp_seq=5 ttl=51 time=22.136 ms
64 bytes from 182.43.124.6: icmp_seq=6 ttl=51 time=16.477 ms
^C
--- raw.githubusercontent.com ping statistics ---
7 packets transmitted, 7 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 15.737/17.021/22.136/2.111 ms
sanji@Sanji my-offckb-project % offckb create my-dapp         
/opt/homebrew/lib/node_modules/@offckb/cli/dist/util/template.js:26
            throw new Error(`Error fetching JSON: ${error.message}`);
                  ^

Error: Error fetching JSON: Maximum number of redirects exceeded
    at /opt/homebrew/lib/node_modules/@offckb/cli/dist/util/template.js:26:19
    at Generator.throw (<anonymous>)
    at rejected (/opt/homebrew/lib/node_modules/@offckb/cli/dist/util/template.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.4 
I can ping it raw.githubusercontent.com, but it's still the same😭

**Comment by RetricSu** [comment]
> my-offckb-project % ping raw.githubusercontent.com PING raw.githubusercontent.com (182.43.124.6): 56 data bytes 64 bytes from 182.43.124.6: icmp_seq=0 ttl=51 time=16.475 ms 64 bytes from 182.43.124.6: icmp_seq=1 ttl=51 time=15.755 ms 64 bytes from 182.43.124.6: icmp_seq=2 ttl=51 time=16.508 ms 64 bytes from 182.43.124.6: icmp_seq=3 ttl=51 time=16.062 ms 64 bytes from 182.43.124.6: icmp_seq=4 ttl=51 time=15.737 ms 64 bytes from 182.43.124.6: icmp_seq=5 ttl=51 time=22.136 ms 64 bytes from 182.43.124.6: icmp_seq=6 ttl=51 time=16.477 ms ^C --- raw.githubusercontent.com ping statistics --- 7 packets transmitted, 7 packets received, 0.0% packet loss round-trip min/avg/max/stddev = 15.737/17.021/22.136/2.111 ms sanji@Sanji my-offckb-project % offckb create my-dapp /opt/homebrew/lib/node_modules/@offckb/cli/dist/util/template.js:26 throw new Error(`Error fetching JSON: ${error.message}`); ^
> 
> Error: Error fetching JSON: Maximum number of redirects exceeded at /opt/homebrew/lib/node_modules/@offckb/cli/dist/util/template.js:26:19 at Generator.throw () at rejected (/opt/homebrew/lib/node_modules/@offckb/cli/dist/util/template.js:6:65) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.20.4 I can ping it raw.githubusercontent.com, but it's still the same😭

really sorry about that. This is odd. The error "Maximum number of redirects exceeded" indicates that the HTTP client (axios in offckb) is being redirected too many times when trying to fetch the JSON from the template.json file URL, which is `https://raw.githubusercontent.com/RetricSu/offckb/master/templates/template.json`

**Comment by RetricSu** [comment]
not sure if you can check if axios can fetching `https://raw.githubusercontent.com/RetricSu/offckb/master/templates/template.json` works in your terminal but ,maybe we should add proxy setting for `axios` in offckb to allow to bypass such network issue?

can [proxychains](https://github.com/haad/proxychains) be a workaround to fix the problem?

**Comment by TheLastHobbit** [comment]
I haven't used a proxy chain，I don't know why I can ping but I can't connect,Is there another way to initialize the project?

**Comment by RetricSu** [comment]
> I haven't used a proxy chain，I don't know why I can ping but I can't connect,Is there another way to initialize the project?

hello, can you try `0.2.0-canary-fd72176.0` to use proxy
install：
```sh
npm install -g @offckb/cli@0.2.0-canary-fd72176.0
```
set proxy：
```sh 
offckb config set proxy <proxy url, eg: http://127.0.0.1:1086>
```
see: https://github.com/RetricSu/offckb/tree/develop?tab=readme-ov-file#add-network-proxy

**Comment by TheLastHobbit** [comment]
ok，Thank you very much, but this is an error: 
sanji@Sanji first_project % npm install -g@offckb /cli@0.2.0-canary-fd72176.0                  
added 140 packages in 25s  11 packages are looking for funding   run `npm fund` for details 
sanji@Sanji first_project % offckb config set proxy http://127.0.0.1:7890 error: unknown command 'config'

**Comment by TheLastHobbit** [comment]
and the current version：
sanji@Sanji first_project % offckb --version
0.2.6

**Comment by RetricSu** [comment]
whoops, can you try `npm install -g@offckb /cli@canary` ? 

> ok，Thank you very much, but this is an error: sanji@Sanji first_project % npm install -g@offckb /cli@0.2.0-canary-fd72176.0 added 140 packages in 25s 11 packages are looking for funding run `npm fund` for details sanji@Sanji first_project % offckb config set proxy http://127.0.0.1:7890 error: unknown command 'config'

there is a typo in your command. you are not successfully installed the packages:

```sh
 ✘  ~  npm install -g @offckb/cli@0.2.0-canary-fd72176.0

changed 140 packages in 31s

11 packages are looking for funding
  run `npm fund` for details
 ~  offckb --version
0.2.0-canary-fd72176.0
 ~ 
```

**Comment by TheLastHobbit** [comment]
I copied your command, but why is it different than yours?
sanji@Sanji first_project % npm install -g @offckb/cli@0.2.0-canary-fd72176.0

changed 140 packages in 27s

11 packages are looking for funding
  run `npm fund` for details
sanji@Sanji first_project % offckb --version
0.2.6

**Comment by RetricSu** [comment]
> I copied your command, but why is it different than yours? sanji@Sanji first_project % npm install -g @offckb/cli@0.2.0-canary-fd72176.0
> 
> changed 140 packages in 27s
> 
> 11 packages are looking for funding run `npm fund` for details sanji@Sanji first_project % offckb --version 0.2.6

not sure why your version is still the old `v0.2.6`. maybe uninstall and install again?

**Comment by TheLastHobbit** [comment]
Sorry to bother you. Now the version is correct, but the error is still the same. If I use a proxy, I can ping it： 
% ping raw.githubusercontent.com                                                                             
PING raw.githubusercontent.com (185.199.111.133): 56 data bytes
Request timeout for icmp_seq 0
64 bytes from 185.199.111.133: icmp_seq=1 ttl=51 time=152.079 ms
64 bytes from 185.199.111.133: icmp_seq=2 ttl=51 time=155.157 ms
Request timeout for icmp_seq 3
64 bytes from 185.199.111.133: icmp_seq=4 ttl=51 time=148.198 ms
64 bytes from 185.199.111.133: icmp_seq=5 ttl=51 time=148.999 ms
Error:
% offckb create my-dapp
{ proxy: { host: '127.0.0.1', port: 7890, protocol: 'http' } }
/Users/sanji/.nvm/versions/node/v18.20.4/lib/node_modules/@offckb/cli/dist/util/template.js:23
            throw new Error(`Error fetching JSON: ${error.message}`);
                  ^

Error: Error fetching JSON: Maximum number of redirects exceeded
    at /Users/sanji/.nvm/versions/node/v18.20.4/lib/node_modules/@offckb/cli/dist/util/template.js:23:19
    at Generator.throw (<anonymous>)
    at rejected (/Users/sanji/.nvm/versions/node/v18.20.4/lib/node_modules/@offckb/cli/dist/util/template.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.4

**Comment by TheLastHobbit** [comment]
the version is right now:
% offckb --version                                 
0.2.0-canary-fd72176.0

**Comment by RetricSu** [comment]
> Sorry to bother you. Now the version is correct, but the error is still the same. If I use a proxy, I can ping it： % ping raw.githubusercontent.com PING raw.githubusercontent.com (185.199.111.133): 56 data bytes Request timeout for icmp_seq 0 64 bytes from 185.199.111.133: icmp_seq=1 ttl=51 time=152.079 ms 64 bytes from 185.199.111.133: icmp_seq=2 ttl=51 time=155.157 ms Request timeout for icmp_seq 3 64 bytes from 185.199.111.133: icmp_seq=4 ttl=51 time=148.198 ms 64 bytes from 185.199.111.133: icmp_seq=5 ttl=51 time=148.999 ms Error: % offckb create my-dapp { proxy: { host: '127.0.0.1', port: 7890, protocol: 'http' } } /Users/sanji/.nvm/versions/node/v18.20.4/lib/node_modules/@offckb/cli/dist/util/template.js:23 throw new Error(`Error fetching JSON: ${error.message}`); ^
> 
> Error: Error fetching JSON: Maximum number of redirects exceeded at /Users/sanji/.nvm/versions/node/v18.20.4/lib/node_modules/@offckb/cli/dist/util/template.js:23:19 at Generator.throw () at rejected (/Users/sanji/.nvm/versions/node/v18.20.4/lib/node_modules/@offckb/cli/dist/util/template.js:6:65) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.20.4

feels like this is something to do with `raw.githubusercontent.com` server that handles the request. I need to dig more. one more question, can you do `offckb node` to start running a devnet on you computer? This will helps to analyze the issue.

**Comment by RetricSu** [comment]
@TheLastHobbit hi, please use [`v0.2.7`](https://www.npmjs.com/package/@offckb/cli/v/0.2.7) to check if it resolves your issue.

**Comment by TheLastHobbit** [comment]
Problem solved! Thank you very much，you are so patient ，I didn't think anyone would solve the problem.
