### ISSUE TITLE
needs sudo ?

### ISSUE THREAD

**Issue by RetricSu** [RetricSu/offckb#18]
env: MacOS

some needs `sudo` to bypass the permission issue

```sh
sudo npm install -g @offckb/cli
sudo offckb node
```

**Comment by sunchengzhu** [comment]
I've also encountered this issue. Granting the current user write access to the node_modules directory can resolve the problem.
```bash
sudo chown -R $(whoami) /usr/local/lib/node_modules
npm install -g @offckb/cli
```

**Comment by RetricSu** [comment]
added the solution from @sunchengzhu  in the readme:

- https://github.com/RetricSu/offckb/pull/77
