### ISSUE TITLE
windows上安装执行offckb node执行乱码

### ISSUE THREAD

**Issue by 1459274759** [RetricSu/offckb#55]
offckb node
'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
D:\Program Files\nvm\v21.7.3\node_modules\@offckb\cli\target\ckb\ckb not found, download and install the new version 0.113.1..
(node:18488) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by RetricSu** [comment]
we will release a patch to fix this soon. by the way, what is your node.js version? I noticed there is also a node.js `DeprecationWarning` message

**Comment by RetricSu** [comment]
@1459274759 can you check if [0.1.1-canary-79abb13.0](https://www.npmjs.com/package/@offckb/cli/v/0.1.1-canary-79abb13.0) version fix your problem?

```sh
npm install -g @offckb/cli@0.1.1-canary-79abb13.0
```

**Comment by 1459274759** [comment]
@RetricSu  Version @0.1.1-canary-79abb13.0  has been fixed, and it has been found that the problem may be caused by a space in the node installation directory, resulting in an error. The problem was resolved by reinstalling the node

**Comment by 1459274759** [comment]
D:\www\ckb> nvm ls

    21.7.3
  * 18.12.1 (Currently using 64-bit executable)
 D:\www\ckb> offckb node
The system cannot find the path specified.
D:\nvm\v18.12.1\node_modules\@offckb\cli\target\ckb\ckb not found, download and install the new version 0.113.1..
D:\www\ckb> offckb node
The system cannot find the path specified.
D:\nvm\v21.7.3\node_modules\@offckb\cli\target\ckb\ckb not found, download and install the new version 0.113.1..
(node:14280) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

The above is the error message returned by me when executing offsckb node under two versions. I couldn't find the directory @ offsckb \ cli \ target \ ckb \ ckb in the corresponding version directory

**Comment by 1459274759** [comment]
offckb init dapp
(node:11572) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
D:\nvm\v21.7.3\node_modules\@offckb\cli\dist\util.js:193
            throw new Error(`Error fetching JSON: ${error.message}`);
                  ^

Error: Error fetching JSON: getaddrinfo ENOENT raw.githubusercontent.com
    at D:\nvm\v21.7.3\node_modules\@offckb\cli\dist\util.js:193:19
    at Generator.throw (<anonymous>)
    at rejected (D:\nvm\v21.7.3\node_modules\@offckb\cli\dist\util.js:29:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3

**Comment by RetricSu** [comment]
it looks like the above two errors are all related to your network environment, when you execute `offckb node` it will try to download CKB binary from github, see `download and install the new version` in your log:
```sh
D:\nvm\v18.12.1\node_modules@offckb\cli\target\ckb\ckb not found, download and install the new version 0.113.1..
```

and when your run `offckb init dapp`, the error is also caused by network`Error: Error fetching JSON: getaddrinfo ENOENT raw.githubusercontent.com`.

so you need to make sure that there is no network issue in your terminal to connect to github in order to use offckb. @1459274759

**Comment by RetricSu** [comment]
feel free to reopen this issue if needed
