### ISSUE TITLE
Cannot init project without sudo

### ISSUE THREAD

**Issue by michael-qu** [RetricSu/offckb#83]
Hi I am new to CKB development. I would like to create a simple dApp using the first option of the template (View and Transfer a CKB Balance) according to the tutorial here https://docs.nervos.org/docs/getting-started/transfer-ckb

If I type "offckb init <project-name>" the terminal gives permission error.

<img width="877" alt="image" src="https://github.com/RetricSu/offckb/assets/70831810/bd2b00e4-1366-4052-9f93-652ddf1b6ff8">

If I type "sudo offckb init <project-name>", I can init the project but later I cannot save the edited file no matter I use sudo or not.

<img width="1012" alt="image" src="https://github.com/RetricSu/offckb/assets/70831810/2697bca1-4594-467a-b9b5-434c87e874ac">

<img width="1019" alt="image" src="https://github.com/RetricSu/offckb/assets/70831810/7475b9ac-a3c1-42be-8ea7-f7b42150816a">

Can you help me with this?

**Comment by RetricSu** [comment]
can you try this solution?
- https://github.com/RetricSu/offckb/issues/18#issuecomment-2084525296

**Comment by RetricSu** [comment]
feel free to open it if you have further questions
