### ISSUE TITLE
punycode deprecation warning when generating project

### ISSUE THREAD

**Issue by chenyukang** [RetricSu/offckb#92]
```console
➜  /tmp offckb create ckb-hello
(node:45665) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

FYI: https://nodejs.org/api/punycode.html

**Comment by RetricSu** [comment]
please use [LTS](https://nodejs.org/en/download/package-manager) node
<img width="608" alt="image" src="https://github.com/RetricSu/offckb/assets/23436060/1199eb39-d9a8-4fbf-9165-fc9c96970e9c">

**Comment by chenyukang** [comment]
resolved, thanks.
